services:
  - type: web
    name: brickedup-masonry
    runtime: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
